# Generated by Django 4.0.3 on 2022-03-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_food',
            new_name='Orderfood',
        ),
    ]
