# Generated by Django 4.0.3 on 2022-03-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_order_food_orderfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
